### ISSUE TITLE
Relay mechanism - data exchange between client and peers

### ISSUE THREAD

**Issue by arkgil** [esl/fennec#16]
This involves processing of Send indications from client and forwarding it to its peers through allocation socket, and receiving data on allocation socket and forwarding it to client via Data indications.

**Comment by rslota** [comment]
In progress in #31

**Comment by rslota** [comment]
Send indication has been implemented and merged in #31 .
To close this issue we still need Data indication.

**Comment by rslota** [comment]
Data indication have been implemented and merged in #33 .
